### ISSUE TITLE
 Wheelmap corrupts OSM tagging if a tag contains &

### ISSUE THREAD

**Issue by Nakaner** [sozialhelden/rosemary#14]
If a tag contains `&` and you edit this POI via Wheelmap web interface, Wheelmap replaces `&` by `&#38;` afterwards. At the second time you edit this object via Wheelmap, Wheelmap replaces `&#38;` by `&#38;#38;` at OSM data. In other words, every time a Wheelmap user modifies an object which has a tag which contains `&`, this `&` is changed to `&#38;`. This changes OSM data (or, in other words, corrupts them).

Example: If I go to Sachsenheim station, click on "Edit" and afterwards on "Save" (without editing anything) [`operator=DB Station&Service AG` is replaced by `operator=DB Station&#38;Service AG`](https://www.openstreetmap.org/node/247669894/history).

It seems that every OSM tag can be corrupted this way. [I have fixed this type of data corruption today in whole Germany (search data via Overpass API and fix it object by object).](https://www.openstreetmap.org/changeset/29748180)

The bug only occurs if the data is edited by logged-in users. Edits done anonymously [do not cause these data corruptions](https://www.openstreetmap.org/node/2656117800/history). It seems that only the web interface and neither the Android nor the iOS app is affected.

**Comment by christoph-buente** [comment]
There is actually a test for the parser to read &#38; as a normal ampersand:

https://github.com/sozialhelden/rosemary/blob/master/spec/models/parser_spec.rb#L12

I'll have a look at the other way round, when sending data to osm.

**Comment by christoph-buente** [comment]
I did some investigation and found out, that the ruby XML builder library is actually doing it. Have a look here: http://apidock.com/rails/Builder/XmlMarkup

Maybe there is a way to suppress this behaviour.

**Comment by Nakaner** [comment]
Could you please fix this? I did a mechanical clean up at the OSM database in March. Today I search for this tagging again using Overpass API and got 60 nodes and 4 ways in Germany using [this request](http://overpass-turbo.eu/s/9uG).

It is not task of the OSM community to regularly clean up the OSM database because an online editor uses a buggy library.

**Comment by christoph-buente** [comment]
Hi Nakaner,

thx for reminding me. Yesterday we released a new version of wheelmap.org. With it came the fix for wrong html entities handling.

**Comment by Nakaner** [comment]
Thank you. Then I will run a last clean-up at OSM.

**Comment by Nakaner** [comment]
I have fixed all occurences of this bug all over the world (about 40 `operator=*`, 10 `name=*` and 4 `wheelchair:description=*`. Most occurences were in Germany because of "GmbH & Co. KG" and "DB Station&Service AG". :-)

**Comment by christoph-buente** [comment]
Oh dear. Thx a lot, hope this will not happen again.

**Comment by christoph-buente** [comment]
Hmm, for some reason this error still occurs: http://www.openstreetmap.org/way/95845423/history
I'll have a look.

**Comment by christoph-buente** [comment]
I think it is, because we already have lots of POIS in our local database, which have this wrong tag set already. I will go through an clean up our database and then let's keep observing.

**Comment by Nakaner** [comment]
Wheelmap uses OSM's minutely diffs, doesn't it? If I it is so, you should already have got the fixed versions which overwrite your local database entries.

This are my fix changesets at OSM: 
http://www.openstreetmap.org/changeset/31320611 http://www.openstreetmap.org/changeset/31320503 http://www.openstreetmap.org/changeset/31319528

**Comment by christoph-buente** [comment]
i have the fix, but we have also wrongly imported nodes, that have never been updated since.

**Comment by Nakaner** [comment]
If you send me the IDs of these nodes via email, I will fix them at OSM. Or you fix them on your own.

**Comment by christoph-buente** [comment]
For example that node is ok in OSM: http://www.openstreetmap.org/node/611926
But in our db it is: Chef &#38; Brewer for the operator tag. I will go through and clean our database or prepare a full import to make sure we have a clean db again.

**Comment by christoph-buente** [comment]
Hey, i released version 0.4.4 to fix correct handling of html entities. See commit https://github.com/sozialhelden/rosemary/commit/c235b03a6954d6df40f3f87bb864ce12c152b7a0
